image: python:latest

before_script:
  - python -V # Print out python version for debugging

stages:
  - test

test_job:
  stage: test
  script:
    - echo "Running tests"
    - python -m unittest discover -s "./tests/"
